### Privacy Disclaimer

 This Jupyter Notebook contains sensitive and confidential information that includes data protected under Florida's Sunshine Laws. Unauthorized disclosure, distribution, or copying of this data is strictly prohibited. **This document is intended solely for the use of the authorized recipient(s) and is not for public disclosure.**

If you are not the intended recipient, please notify the sender immediately, delete this notebook from your system, and do not disclose its contents to any other person, use it for any purpose, or store or copy any of the information contained herein.

By accessing and using this notebook, you agree to comply with all applicable confidentiality and data protection laws and policies.

### Attributions
(C) Dariel Cruz Rodriguez, 2024, under work for Orange County Public Schools.

In [2]:
# Modules utilized in this code
import pandas as pd
import matplotlib as plt

In [23]:
# Defining data sources
df = pd.read_csv("OrangeCountyPublicSchoolsAllDataLeadershipView10Jun2024.csv")
df.head()
df_district2 = df[df['Name'].isin(['LAKE NONA HIGH', 'COLONIAL HIGH'])]
df_district2.head()

,Name,(9-12),Rigorous Expectations,School Climate,Self-Management,Sense of Belonging,Teacher-Student Relationships,(6-8),Rigorous Expectations.1,School Climate.1,...,Teaching Efficacy,Central Office,Department Climate,Department Leadership,Feedback and Coaching.2,Resources.2,Spring 2024 Family Survey,Barriers to Engagement,School Climate.4,School Fit
5,COLONIAL HIGH,NaN,51.0,27.0,66.0,30.0,40.0,NaN,NaN,NaN,...,74.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,48.0,45.0
18,LAKE NONA HIGH,NaN,51.0,31.0,71.0,35.0,42.0,NaN,NaN,NaN,...,78.0,NaN,NaN,NaN,NaN,NaN,NaN,70.0,62.0,56.0