<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIbM9xMoM7XWvpmPRPtAsMnIyVLvlaWopGF7k4GtYNBTL1Uj7OfMktStIUKlsRKYgcmg&usqp=CAU"></img>

# Analysis of OCPSAllDataLeaderView.csv

### Privacy Disclaimer

 This Jupyter Notebook contains sensitive and confidential information that includes data protected under Florida's Sunshine Laws. Unauthorized disclosure, distribution, or copying of this data is strictly prohibited. **This document is intended solely for the use of the authorized recipient(s) and is not for public disclosure.**

If you are not the intended recipient, please notify the sender immediately, delete this notebook from your system, and do not disclose its contents to any other person, use it for any purpose, or store or copy any of the information contained herein.

By accessing and using this notebook, you agree to comply with all applicable confidentiality and data protection laws and policies.


### Attributions
(C) Dariel Cruz Rodriguez, 2024, under work for Orange County Public Schools.



---

### Code

In [81]:
pip install adjustText

Requirement already satisfied: adjustText in /usr/local/lib/python3.10/dist-packages (1.1.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from adjustText) (1.25.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from adjustText) (3.7.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from adjustText) (1.11.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->adjustText) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->adjustText) (1.16.0)

In [82]:
# Modules utilized in this code
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from adjustText import adjust_text

In [83]:
# Defining data sources
url = "https://raw.githubusercontent.com/cruzdariel/OCPSAllDataLeaderView2024/colab/OrangeCountyPublicSchoolsAllDataLeadershipView10Jun2024.csv?token=GHSAT0AAAAAACTX3ZR4NKTFUZGHPHLR7HW4ZTRZPTQ"

df = pd.read_csv(url) # All schools
df = df[~df['Name'].isin([
    "OCVS VIRTUAL INSTRUCTION COURSE OFFERING",
    "ORANGE CENTER ELEMENTARY",
    "TIMBER LAKES ELEMENTARY",
    "ACCESS AND OPPORTUNITY",
    "ACCOUNTS PAYABLE",
    "CURRICULUM & DIGITAL LEARNING",
    "CURRICULUM AND INSTRUCTION",
    "CUSTODIAL SERVICES",
    "DISTRICT POLICE and PROTECTIVE SERVICES",
    "ELEMENTARY SCHOOLS",
    "EMPLOYMENT SERVICES",
    "ENVIRONMENTAL COMPLIANCE AND SUSTAINABIL",
    "ESE INSTRUCTIONAL SUPPORT",
    "ESE POL & PRO & SUP SVC NONPUB",
    "ESE POL & PROCEDURES PUB K12",
    "ESE SPEC PROG & BEHAVIOR SUPP",
    "ESE SUPPLEMENTAL SERVICES",
    "FACILITIES SERVICES CONSTRUCTION",
    "FACILITIES SVC MAINTENANCE and FACILITIE",
    "FEDERAL PROGRAMS",
    "FINANCE",
    "FOOD AND NUTRITION SERVICES",
    "GROUNDS LANDSCAPING AND PEST CONTROL SVC",
    "HR COMPLIANCE",
    "ITS CUSTOMER CARE",
    "ITS ENTERPRISE PROJECTS",
    "ITS INFRASTRUCTURE",
    "MAINTENANCE NORTHEAST",
    "MAINTENANCE NORTHWEST",
    "MAINTENANCE SOUTH",
    "MULTILINGUAL SERVICES",
    "OFFICE OF MANAGEMENT AND BUDGET",
    "PAYROLL SERVICES",
    "PROCUREMENT SVCS AND FAC CONST CONTRACT",
    "PROFESSIONAL LEARNING",
    "PROFESSIONAL STANDARDS",
    "PSYCHOLOGICAL & SOCIAL SERVICES",
    "PUBLIC RELATIONS",
    "RESEARCH, MEASUREMENT AND STRATEGY",
    "RISK MANAGEMENT",
    "SCHOOL CHOICE SERVICES",
    "SCHOOL TRANSFORMATION OFFICE",
    "STUDENT ENROLLMENT",
    "STUDENT INFORMATION SYSTEMS AND PROJECTS",
    "STUDENT SERVICES",
    "TRANSPORTATION ADMINISTRATION",
    "TRANSPORTATION STUDENT SVCS",
    "TRANSPORTATION SUPPORT SERVICES",
    "VOCATIONAL TECHNICAL EDUCATION",
    "AMIKIDS ORLANDO",
    "OCVS VIRTUAL INSTRUCTION PROGRAM",
    "HOSPITAL HOMEBOUND",
    "BETA",
    "ESE TRANSITION",
    "RANDALL ACADEMY",
    "SIMON YOUTH FOUND ACAD AT OUTLET MKTPLCE",
    "ORANGE TECHNICAL COLLEGE MID FLORIDA CMP",
    "ORANGE TECHNICAL COLLEGE ORLANDO CAMPUS",
    "ORANGE TECHNICAL COLLEGE WESTSIDE CAMPUS",
    "ORANGE TECHNICAL COLLEGE WINTER PARK CMP",
    "ORANGE YOUTH ACADEMY",
    "PACE CENTER FOR GIRLS",
    "MAGNOLIA",
    "UNIVERSAL EDUCATION CENTER",
    "POSITIVE PATHWAYS TRANSITION CENTER",
    "ESTEEM ACADEMY",
    "SILVER PINES ACADEMY K12 LEARNING CENTER"
])] # Filterning non traditional K12

df_district2 = df[df['Name'].isin(['LAKE NONA HIGH', 'COLONIAL HIGH'])] # District 2 Schools
df_notdistrict2 = df[~df['Name'].isin(['LAKE NONA HIGH', 'COLONIAL HIGH'])] # Non District 2 Schools

colonial_hs = df[df['Name'] == 'COLONIAL HIGH']
lake_nona_hs = df[df['Name'] == 'LAKE NONA HIGH']

hs = {'avg_rigor': np.mean(df['Rigorous Expectations']),
      'avg_rigor_notd2': np.mean(df_notdistrict2['Rigorous Expectations']),
      'avg_schoolclimate': np.mean(df['School Climate']),
      'avg_schoolclimate_notd2': np.mean(df_notdistrict2['School Climate']),
      'avg_selfmanagement': np.mean(df['Self-Management']),
      'avg_selfmanagement_notd2': np.mean(df_notdistrict2['Self-Management']),
      'avg_senseofbelonging': np.mean(df['Sense of Belonging']),
      'avg_senseofbelonging_notd2': np.mean(df_notdistrict2['Sense of Belonging']),
      'average_teacherstudentrelationships':np.mean(df['Teacher-Student Relationships']),
      'average_teacherstudentrelationships_notd2': np.mean(df_notdistrict2['Teacher-Student Relationships'])}

ms = {'avg_rigor': np.mean(df['Rigorous Expectations.1']),
      'avg_rigor_notd2': np.mean(df_notdistrict2['Rigorous Expectations.1']),
      'avg_schoolclimate': np.mean(df['School Climate.1']),
      'avg_schoolclimate_notd2': np.mean(df_notdistrict2['School Climate.1']),
      'avg_selfmanagement': np.mean(df['Self-Management.1']),
      'avg_selfmanagement_notd2': np.mean(df_notdistrict2['Self-Management.1']),
      'avg_senseofbelonging': np.mean(df['Sense of Belonging.1']),
      'avg_senseofbelonging_notd2': np.mean(df_notdistrict2['Sense of Belonging.1']),
      'average_teacherstudentrelationships':np.mean(df['Teacher-Student Relationships.1']),
      'average_teacherstudentrelationships_notd2': np.mean(df_notdistrict2['Teacher-Student Relationships.1'])}

In [84]:
pd.set_option('display.max_columns', 1000)
df.describe()

,(9-12),Rigorous Expectations,School Climate,Self-Management,Sense of Belonging,Teacher-Student Relationships,(6-8),Rigorous Expectations.1,School Climate.1,Self-Management.1,Sense of Belonging.1,Teacher-Student Relationships.1,Staff,Belonging,Feedback and Coaching,Resources,School Climate.2,School Leadership,Teacher,Belonging.1,Feedback and Coaching.1,Resources.1,School Climate.3,School Leadership.1,Teacher Self-Reflection,Teaching Efficacy,Central Office,Department Climate,Department Leadership,Feedback and Coaching.2,Resources.2,Spring 2024 Family Survey,Barriers to Engagement,School Climate.4,School Fit
count,0.0,25.00000,25.000000,25.000000,25.000000,25.000000,0.0,52.000000,52.000000,52.000000,52.000000,52.000000,0.0,203.000000,203.000000,203.000000,203.000000,203.000000,0.0,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,0.0,0.0,0.0,0.0,0.0,0.0,204.000000,204.000000,204.000000
mean,NaN,53.76000,34.040000,69.560000,33.960000,42.320000,NaN,59.692308,35.423077,65.807692,38.269231,46.961538,NaN,74.108374,61.157635,48.147783,67.088670,72.492611,NaN,70.823529,58.357843,44.828431,59.740196,63.299020,81.691176,78.269608,NaN,NaN,NaN,NaN,NaN,NaN,82.401961,79.450980,73.769608
std,NaN,6.74092,9.528379,4.083299,6.528655,7.597807,NaN,6.316919,9.189393,6.556058,7.205976,8.858277,NaN,11.545780,13.338501,13.203204,15.346558,14.966090,NaN,10.861793,13.777771,12.409474,14.054649,16.110267,6.783617,6.527762,NaN,NaN,NaN,NaN,NaN,NaN,7.081871,11.741994,11.475434
min,NaN,44.00000,21.000000,64.000000,23.000000,32.000000,NaN,48.000000,23.000000,51.000000,27.000000,32.000000,NaN,36.000000,27.000000,14.000000,23.000000,26.000000,NaN,47.000000,23.000000,19.000000,26.000000,24.000000,61.000000,61.000000,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,22.000000,22.000000
25%,NaN,51.00000,28.000000,66.000000,30.000000,38.000000,NaN,55.000000,28.750000,61.750000,31.000000,39.750000,NaN,67.000000,52.000000,39.000000,57.000000,64.000000,NaN,63.000000,48.750000,35.000000,49.000000,52.000000,77.000000,74.000000,NaN,NaN,NaN,NaN,NaN,NaN,79.000000,72.000000,67.000000
50%,NaN,53.00000,32.000000,70.000000,35.000000,42.000000,NaN,59.000000,34.000000,66.000000,39.000000,47.000000,NaN,74.000000,62.000000,48.000000,69.000000,74.000000,NaN,71.000000,59.500000,44.000000,59.000000,65.000000,82.000000,78.000000,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,83.000000,76.000000
75%,NaN,55.00000,38.000000,72.000000,37.000000,44.000000,NaN,63.000000,40.250000,71.000000,43.000000,52.000000,NaN,83.000000,71.000000,57.000000,78.500000,84.500000,NaN,79.000000,69.250000,53.000000,71.000000,75.000000,86.000000,83.000000,NaN,NaN,NaN,NaN,NaN,NaN,87.000000,88.000000,82.000000
max,NaN,76.00000,66.000000,81.000000,54.000000,73.000000,NaN,77.000000,72.000000,79.000000,58.000000,81.000000,NaN,99.000000,95.000000,86.000000,99.000000,98.000000,NaN,96.000000,91.000000,92.000000,98.000000,96.000000,97.000000,96.000000,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,98.000000,98.000000

In [87]:
plt.style.use('default')

# All High Schools - School Climate vs. Rigor Expectations Score
plt.scatter(df['Rigorous Expectations'],
            df['School Climate'],
            c='black')
plt.scatter(colonial_hs['Rigorous Expectations'],
            colonial_hs['School Climate'],
            c='red',
            label='Colonial High')
plt.scatter(colonial_hs['Rigorous Expectations'],
            lake_nona_hs['School Climate'],
            c='blue',
            label='Lake Nona High')
plt.scatter(hs['avg_rigor_notd2'],
            hs['avg_schoolclimate_notd2'],
            color='grey',
            label='Average - All Schools')
plt.scatter(hs['avg_rigor'],
            hs['avg_schoolclimate'],
            color='tan',
            label='Average - Without D2')
plt.title('School Climate vs. Rigorous Expectations Score - All High Schools')
plt.xlabel('Rigorous Expectations Score')
plt.ylabel('School Climate Score')
plt.xlim(20, 80)
plt.ylim(20, 80)
plt.legend()
plt.show()

# All High Schools - School Climate vs. Rigor Expectations Score (Scores above 50)
texts = []
for x in df.index:
    if df.loc[x, 'Rigorous Expectations'] > 50 and df.loc[x, 'School Climate'] > 40:
        plt.scatter(df.loc[x, 'Rigorous Expectations'], df.loc[x, 'School Climate'])
        plt.annotate(df.loc[x, 'Name'],
                     (df.loc[x, 'Rigorous Expectations'], df.loc[x, 'School Climate']),
                     textcoords="offset points",
                     xytext=(0,10),
                     ha='center')
plt.scatter(colonial_hs['Rigorous Expectations'],
            colonial_hs['School Climate'],
            c='red',
            label='Colonial High')
plt.scatter(colonial_hs['Rigorous Expectations'],
            lake_nona_hs['School Climate'],
            c='blue',
            label='Lake Nona High')
plt.scatter(hs['avg_rigor_notd2'],
            hs['avg_schoolclimate_notd2'],
            color='grey',
            label='Average - All Schools')
plt.scatter(hs['avg_rigor'],
            hs['avg_schoolclimate'],
            color='tan',
            label='Average - Without D2')

plt.title('School Climate vs. Rigorous Expectations Score - All High Schools (Scores above 50)')
plt.xlabel('Rigorous Expectations Score')
plt.ylabel('School Climate Score')
plt.xlim(20, 80)
plt.ylim(20, 70)
plt.legend()
adjust_text(texts)
plt.show()